### PR TITLE
github actions: run test action on all branches

### PR DESCRIPTION
**Pull request by SebKuzminsky**
This would have helped me find the problem with my "apt-get without -t" branch earlier.

### CODE REVIEW

**Comment by SebKuzminsky** [comment]
This PR failed because I messed with `apt-get -t`, the fix for that is in #67.

**Comment by SebKuzminsky** [comment]
The downside is that it makes it inconvenient to test my branch before opening the PR, which leads me to offer untested PRs.  When those fail (like my broken first attempt at `apt-get` without `-t`) it wastes your time.

I don't see what the downside is to testing all branches.

This is not a huge deal to me and I respect your decision.  I have a commit in my local repo that turns on testing of all branches, I just have to remember to include it in bugfix- and feature-branches during testing, and remove it before opening the PR.

**Comment by dawidd6** [comment]
Just open the PR as a draft.

**Comment by SebKuzminsky** [comment]
Ah, yeah that would work.  Thanks!

**Pull request closed without merging**
